# Generated by Django 3.1.2 on 2020-11-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201106_1405'),
        ('main', '0002_auto_20201105_1006'),
    ]

    operations = [
    ]
